"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var claseContacts_1 = require("./claseContacts");
var clasePerson_1 = require("./clasePerson");
var misContactos = new claseContacts_1.Contacts();
var persona = new clasePerson_1.Person();
persona.surname;
persona.address;
console.log(persona);
var persona2 = new clasePerson_1.Person("David", 33);
persona2.surname = "Hungaro";
persona2.address = "Los Barqueros 18, Cartagena";
var persona3 = new clasePerson_1.Person("Pedro", 33);
persona3.surname = "Sanchez";
persona3.address = "Moncola, 1";
var persona4 = new clasePerson_1.Person("Tina", 45);
persona4.surname = "Zapata";
persona4.address = "Calle Mayor 6";
var people = [persona, persona2, persona3, persona4];
console.log(people);
